# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1620, 918)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.birdTypeLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.birdTypeLabel.sizePolicy().hasHeightForWidth())
        self.birdTypeLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.birdTypeLabel.setFont(font)
        self.birdTypeLabel.setObjectName("birdTypeLabel")
        self.verticalLayout_4.addWidget(self.birdTypeLabel)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../.designer/backup/MHWI_Weakness_GUI/Icons/土砂龍.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(100, 20))
        self.pushButton.setShortcut("")
        self.pushButton.setCheckable(False)
        self.pushButton.setAutoExclusive(False)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(False)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_4.addWidget(self.pushButton)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_4.addWidget(self.pushButton_5)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_4.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_4.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_4.addWidget(self.pushButton_2)
        self.pushButton_63 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_63.setFont(font)
        self.pushButton_63.setObjectName("pushButton_63")
        self.verticalLayout_4.addWidget(self.pushButton_63)
        self.gridLayout.addLayout(self.verticalLayout_4, 1, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.toothTypeLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toothTypeLabel.sizePolicy().hasHeightForWidth())
        self.toothTypeLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.toothTypeLabel.setFont(font)
        self.toothTypeLabel.setObjectName("toothTypeLabel")
        self.verticalLayout_7.addWidget(self.toothTypeLabel)
        self.pushButton_27 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_27.setFont(font)
        self.pushButton_27.setObjectName("pushButton_27")
        self.verticalLayout_7.addWidget(self.pushButton_27)
        self.pushButton_26 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_26.setFont(font)
        self.pushButton_26.setObjectName("pushButton_26")
        self.verticalLayout_7.addWidget(self.pushButton_26)
        self.pushButton_25 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_25.setFont(font)
        self.pushButton_25.setObjectName("pushButton_25")
        self.verticalLayout_7.addWidget(self.pushButton_25)
        self.pushButton_24 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_24.setFont(font)
        self.pushButton_24.setObjectName("pushButton_24")
        self.verticalLayout_7.addWidget(self.pushButton_24)
        self.pushButton_23 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setObjectName("pushButton_23")
        self.verticalLayout_7.addWidget(self.pushButton_23)
        self.pushButton_22 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_22.setFont(font)
        self.pushButton_22.setObjectName("pushButton_22")
        self.verticalLayout_7.addWidget(self.pushButton_22)
        self.pushButton_21 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_21.setFont(font)
        self.pushButton_21.setObjectName("pushButton_21")
        self.verticalLayout_7.addWidget(self.pushButton_21)
        self.pushButton_20 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setObjectName("pushButton_20")
        self.verticalLayout_7.addWidget(self.pushButton_20)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout_7, 3, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ElderTypeLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ElderTypeLabel.sizePolicy().hasHeightForWidth())
        self.ElderTypeLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.ElderTypeLabel.setFont(font)
        self.ElderTypeLabel.setObjectName("ElderTypeLabel")
        self.verticalLayout_2.addWidget(self.ElderTypeLabel)
        self.pushButton_60 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_60.setFont(font)
        self.pushButton_60.setObjectName("pushButton_60")
        self.verticalLayout_2.addWidget(self.pushButton_60)
        self.pushButton_55 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_55.setFont(font)
        self.pushButton_55.setObjectName("pushButton_55")
        self.verticalLayout_2.addWidget(self.pushButton_55)
        self.pushButton_54 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_54.setFont(font)
        self.pushButton_54.setObjectName("pushButton_54")
        self.verticalLayout_2.addWidget(self.pushButton_54)
        self.pushButton_53 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_53.setFont(font)
        self.pushButton_53.setObjectName("pushButton_53")
        self.verticalLayout_2.addWidget(self.pushButton_53)
        self.pushButton_52 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_52.setFont(font)
        self.pushButton_52.setObjectName("pushButton_52")
        self.verticalLayout_2.addWidget(self.pushButton_52)
        self.pushButton_59 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_59.setFont(font)
        self.pushButton_59.setObjectName("pushButton_59")
        self.verticalLayout_2.addWidget(self.pushButton_59)
        self.pushButton_51 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_51.setFont(font)
        self.pushButton_51.setObjectName("pushButton_51")
        self.verticalLayout_2.addWidget(self.pushButton_51)
        self.pushButton_58 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_58.setFont(font)
        self.pushButton_58.setObjectName("pushButton_58")
        self.verticalLayout_2.addWidget(self.pushButton_58)
        self.pushButton_50 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_50.setFont(font)
        self.pushButton_50.setObjectName("pushButton_50")
        self.verticalLayout_2.addWidget(self.pushButton_50)
        self.pushButton_57 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_57.setFont(font)
        self.pushButton_57.setObjectName("pushButton_57")
        self.verticalLayout_2.addWidget(self.pushButton_57)
        self.pushButton_49 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_49.setFont(font)
        self.pushButton_49.setObjectName("pushButton_49")
        self.verticalLayout_2.addWidget(self.pushButton_49)
        self.pushButton_56 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_56.setFont(font)
        self.pushButton_56.setObjectName("pushButton_56")
        self.verticalLayout_2.addWidget(self.pushButton_56)
        self.pushButton_48 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_48.setFont(font)
        self.pushButton_48.setObjectName("pushButton_48")
        self.verticalLayout_2.addWidget(self.pushButton_48)
        self.pushButton_47 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_47.setFont(font)
        self.pushButton_47.setObjectName("pushButton_47")
        self.verticalLayout_2.addWidget(self.pushButton_47)
        self.pushButton_46 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_46.setFont(font)
        self.pushButton_46.setObjectName("pushButton_46")
        self.verticalLayout_2.addWidget(self.pushButton_46)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 3, 4, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.flyTypeLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flyTypeLabel.sizePolicy().hasHeightForWidth())
        self.flyTypeLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.flyTypeLabel.setFont(font)
        self.flyTypeLabel.setObjectName("flyTypeLabel")
        self.verticalLayout.addWidget(self.flyTypeLabel)
        self.pushButton_31 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_31.setFont(font)
        self.pushButton_31.setObjectName("pushButton_31")
        self.verticalLayout.addWidget(self.pushButton_31)
        self.pushButton_32 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_32.setFont(font)
        self.pushButton_32.setObjectName("pushButton_32")
        self.verticalLayout.addWidget(self.pushButton_32)
        self.pushButton_37 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_37.setFont(font)
        self.pushButton_37.setObjectName("pushButton_37")
        self.verticalLayout.addWidget(self.pushButton_37)
        self.pushButton_29 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_29.setFont(font)
        self.pushButton_29.setObjectName("pushButton_29")
        self.verticalLayout.addWidget(self.pushButton_29)
        self.pushButton_30 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_30.setFont(font)
        self.pushButton_30.setObjectName("pushButton_30")
        self.verticalLayout.addWidget(self.pushButton_30)
        self.pushButton_36 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_36.setFont(font)
        self.pushButton_36.setObjectName("pushButton_36")
        self.verticalLayout.addWidget(self.pushButton_36)
        self.pushButton_33 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_33.setFont(font)
        self.pushButton_33.setObjectName("pushButton_33")
        self.verticalLayout.addWidget(self.pushButton_33)
        self.pushButton_35 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_35.setFont(font)
        self.pushButton_35.setObjectName("pushButton_35")
        self.verticalLayout.addWidget(self.pushButton_35)
        self.pushButton_34 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_34.setFont(font)
        self.pushButton_34.setObjectName("pushButton_34")
        self.verticalLayout.addWidget(self.pushButton_34)
        self.pushButton_28 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_28.setFont(font)
        self.pushButton_28.setObjectName("pushButton_28")
        self.verticalLayout.addWidget(self.pushButton_28)
        self.pushButton_39 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_39.setFont(font)
        self.pushButton_39.setObjectName("pushButton_39")
        self.verticalLayout.addWidget(self.pushButton_39)
        self.pushButton_43 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_43.setFont(font)
        self.pushButton_43.setObjectName("pushButton_43")
        self.verticalLayout.addWidget(self.pushButton_43)
        self.pushButton_42 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_42.setFont(font)
        self.pushButton_42.setObjectName("pushButton_42")
        self.verticalLayout.addWidget(self.pushButton_42)
        self.pushButton_40 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_40.setFont(font)
        self.pushButton_40.setObjectName("pushButton_40")
        self.verticalLayout.addWidget(self.pushButton_40)
        self.pushButton_38 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_38.setFont(font)
        self.pushButton_38.setObjectName("pushButton_38")
        self.verticalLayout.addWidget(self.pushButton_38)
        self.pushButton_45 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_45.setFont(font)
        self.pushButton_45.setObjectName("pushButton_45")
        self.verticalLayout.addWidget(self.pushButton_45)
        self.pushButton_44 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_44.setFont(font)
        self.pushButton_44.setObjectName("pushButton_44")
        self.verticalLayout.addWidget(self.pushButton_44)
        self.pushButton_41 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_41.setFont(font)
        self.pushButton_41.setObjectName("pushButton_41")
        self.verticalLayout.addWidget(self.pushButton_41)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 2, 4, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.beatsTypeLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.beatsTypeLabel.sizePolicy().hasHeightForWidth())
        self.beatsTypeLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.beatsTypeLabel.setFont(font)
        self.beatsTypeLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.beatsTypeLabel.setObjectName("beatsTypeLabel")
        self.verticalLayout_5.addWidget(self.beatsTypeLabel)
        self.pushButton_19 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setObjectName("pushButton_19")
        self.verticalLayout_5.addWidget(self.pushButton_19)
        self.pushButton_18 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setObjectName("pushButton_18")
        self.verticalLayout_5.addWidget(self.pushButton_18)
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setObjectName("pushButton_17")
        self.verticalLayout_5.addWidget(self.pushButton_17)
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setObjectName("pushButton_16")
        self.verticalLayout_5.addWidget(self.pushButton_16)
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setObjectName("pushButton_15")
        self.verticalLayout_5.addWidget(self.pushButton_15)
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setObjectName("pushButton_14")
        self.verticalLayout_5.addWidget(self.pushButton_14)
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setObjectName("pushButton_13")
        self.verticalLayout_5.addWidget(self.pushButton_13)
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_5.addWidget(self.pushButton_12)
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_5.addWidget(self.pushButton_11)
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_5.addWidget(self.pushButton_10)
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_5.addWidget(self.pushButton_9)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 1, 3, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.leaveTypeLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leaveTypeLabel.sizePolicy().hasHeightForWidth())
        self.leaveTypeLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.leaveTypeLabel.setFont(font)
        self.leaveTypeLabel.setObjectName("leaveTypeLabel")
        self.verticalLayout_6.addWidget(self.leaveTypeLabel)
        self.pushButton_62 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_62.setFont(font)
        self.pushButton_62.setObjectName("pushButton_62")
        self.verticalLayout_6.addWidget(self.pushButton_62)
        self.pushButton_61 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_61.setFont(font)
        self.pushButton_61.setObjectName("pushButton_61")
        self.verticalLayout_6.addWidget(self.pushButton_61)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem3)
        self.gridLayout.addLayout(self.verticalLayout_6, 2, 0, 2, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(7)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.fishTypeLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fishTypeLabel.sizePolicy().hasHeightForWidth())
        self.fishTypeLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.fishTypeLabel.setFont(font)
        self.fishTypeLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.fishTypeLabel.setAutoFillBackground(False)
        self.fishTypeLabel.setObjectName("fishTypeLabel")
        self.verticalLayout_3.addWidget(self.fishTypeLabel)
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_3.addWidget(self.pushButton_8)
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_3.addWidget(self.pushButton_7)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_3.addWidget(self.pushButton_6)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(11)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(0, 0, 1041, 851))
        self.label.setText("")
        self.label.setObjectName("label")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 1041, 851))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 1041, 851))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 4, 4, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1620, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.birdTypeLabel.setText(_translate("MainWindow", "鳥龍種"))
        self.pushButton.setText(_translate("MainWindow", "搔鳥"))
        self.pushButton_5.setText(_translate("MainWindow", "毒妖鳥"))
        self.pushButton_4.setText(_translate("MainWindow", "水妖鳥"))
        self.pushButton_3.setText(_translate("MainWindow", "眩鳥"))
        self.pushButton_2.setText(_translate("MainWindow", "黑狼鳥"))
        self.pushButton_63.setText(_translate("MainWindow", "戰痕黑狼鳥"))
        self.toothTypeLabel.setText(_translate("MainWindow", "牙龍種"))
        self.pushButton_27.setText(_translate("MainWindow", "大凶豺龍"))
        self.pushButton_26.setText(_translate("MainWindow", "岩賊龍"))
        self.pushButton_25.setText(_translate("MainWindow", "飛雷龍"))
        self.pushButton_24.setText(_translate("MainWindow", "痺毒龍"))
        self.pushButton_23.setText(_translate("MainWindow", "大凶顎龍"))
        self.pushButton_22.setText(_translate("MainWindow", "慘爪龍"))
        self.pushButton_21.setText(_translate("MainWindow", "兇爪龍"))
        self.pushButton_20.setText(_translate("MainWindow", "雷狼龍"))
        self.ElderTypeLabel.setText(_translate("MainWindow", "古龍種"))
        self.pushButton_60.setText(_translate("MainWindow", "麒麟"))
        self.pushButton_55.setText(_translate("MainWindow", "熔山龍"))
        self.pushButton_54.setText(_translate("MainWindow", "滅盡龍"))
        self.pushButton_53.setText(_translate("MainWindow", "殲世滅盡龍"))
        self.pushButton_52.setText(_translate("MainWindow", "炎王龍"))
        self.pushButton_59.setText(_translate("MainWindow", "炎妃龍"))
        self.pushButton_51.setText(_translate("MainWindow", "鋼龍"))
        self.pushButton_58.setText(_translate("MainWindow", "屍套龍"))
        self.pushButton_50.setText(_translate("MainWindow", "霧瘴屍套龍"))
        self.pushButton_57.setText(_translate("MainWindow", "絢輝龍"))
        self.pushButton_49.setText(_translate("MainWindow", "冥燈龍"))
        self.pushButton_56.setText(_translate("MainWindow", "冰呪龍"))
        self.pushButton_48.setText(_translate("MainWindow", "溟波龍"))
        self.pushButton_47.setText(_translate("MainWindow", "天地煌啼龍"))
        self.pushButton_46.setText(_translate("MainWindow", "貝希摩斯"))
        self.flyTypeLabel.setText(_translate("MainWindow", "飛龍種"))
        self.pushButton_31.setText(_translate("MainWindow", "雌火龍"))
        self.pushButton_32.setText(_translate("MainWindow", "櫻火龍"))
        self.pushButton_37.setText(_translate("MainWindow", "金火龍"))
        self.pushButton_29.setText(_translate("MainWindow", "雄火龍"))
        self.pushButton_30.setText(_translate("MainWindow", "蒼火龍"))
        self.pushButton_36.setText(_translate("MainWindow", "銀火龍"))
        self.pushButton_33.setText(_translate("MainWindow", "浮空龍"))
        self.pushButton_35.setText(_translate("MainWindow", "浮眠龍"))
        self.pushButton_34.setText(_translate("MainWindow", "風漂龍"))
        self.pushButton_28.setText(_translate("MainWindow", "霜翼風漂龍"))
        self.pushButton_39.setText(_translate("MainWindow", "角龍"))
        self.pushButton_43.setText(_translate("MainWindow", "黑角龍"))
        self.pushButton_42.setText(_translate("MainWindow", "爆鱗龍"))
        self.pushButton_40.setText(_translate("MainWindow", "紅蓮爆鱗龍"))
        self.pushButton_38.setText(_translate("MainWindow", "冰牙龍"))
        self.pushButton_45.setText(_translate("MainWindow", "迅龍"))
        self.pushButton_44.setText(_translate("MainWindow", "轟龍"))
        self.pushButton_41.setText(_translate("MainWindow", "黑轟龍"))
        self.beatsTypeLabel.setText(_translate("MainWindow", "獸龍種"))
        self.pushButton_19.setText(_translate("MainWindow", "土砂龍"))
        self.pushButton_18.setText(_translate("MainWindow", "蠻顎龍"))
        self.pushButton_17.setText(_translate("MainWindow", "雷顎龍"))
        self.pushButton_16.setText(_translate("MainWindow", "骨鎚龍"))
        self.pushButton_15.setText(_translate("MainWindow", "爆鎚龍"))
        self.pushButton_14.setText(_translate("MainWindow", "恐暴龍"))
        self.pushButton_13.setText(_translate("MainWindow", "惶怒恐暴龍"))
        self.pushButton_12.setText(_translate("MainWindow", "猛牛龍"))
        self.pushButton_11.setText(_translate("MainWindow", "斬龍"))
        self.pushButton_10.setText(_translate("MainWindow", "硫斬龍"))
        self.pushButton_9.setText(_translate("MainWindow", "碎龍"))
        self.leaveTypeLabel.setText(_translate("MainWindow", "遺存種"))
        self.pushButton_62.setText(_translate("MainWindow", "鹿首精"))
        self.pushButton_61.setText(_translate("MainWindow", "古代鹿首精"))
        self.fishTypeLabel.setText(_translate("MainWindow", "魚龍種"))
        self.pushButton_8.setText(_translate("MainWindow", "泥魚龍"))
        self.pushButton_7.setText(_translate("MainWindow", "熔岩龍"))
        self.pushButton_6.setText(_translate("MainWindow", "冰魚龍"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "出現地點"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "弱點屬性"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "掉落物"))

